### ISSUE TITLE
Some funds fail during loads

### ISSUE THREAD

**Issue by starsplatter** [cul-it/order-import-poc#96] opened 2022-04-27 17:16 UTC
Laurie: Yes, I still can’t load anything with the leigh app using fund p2651.  It is a fund in FOLIO and I can change the fund I load the records with to that fund once they are in FOLIO.  But it is a pain in the butt for large invoices.

**Comment by fereira** [comment] 2022-08-08 19:12
Ive been taking a look at this and have a test for retrieving the fund code data using the p2651 id, compared it the the result of another id and am not seeing anything unusual.  I modified one of  the marc files to use p2651, but can't test it further because there isn't a budget associated with it on the training server.

**Comment by starsplatter** [comment] 2022-08-09 13:05
Thanks, John! I didn't realize you were already looking at this. So you've hit the nail on the head.... the app says this fund/budget doesn't exist but it does. What is happening now is the person loading the files but it's a different fund in the marc record and then changes it by hand to this fund in the FOLIO UI after it is loaded. This seems to happen with only this fund. 220 and p2853 (I was wondering at first if the 'p' was the problem but I guess not).

**Comment by fereira** [comment] 2022-08-09 13:41
that helps and I think I see what the issue is.  The fundCode name in the budgets data is a concatenation of the fundCode and the fiscal year code (eg. p2651-FY2023).  The fiscal year code is hardcoded in the application.properties file.  I don't know what that value is in the production instance.  I will have to look to see if I can find a way to obtain the Fiscal year code from Folio.

**Comment by starsplatter** [comment] 2022-08-09 13:43
That makes sense to me except for the fact that other funds work!

**Comment by fereira** [comment] 2022-08-09 13:49
Do you have an example of one that is still working?   I'm guessing that the application.properties file on the production server has the fiscalYear property set to FY2021.  I have a test that returns all Budgets and many of them have FY2022, but p2651 has FY2023.  I'm guessing that if the properties file is changed to use FY2023, that p2651 will work (but it would brake others that still have FY2021)

**Comment by starsplatter** [comment] 2022-08-09 13:54
p2853 still works. But if it is just checking for the existence of an FY and this fund was created after that FY but others were created before it would make sense that they would work and it doesn't. FOLIO correctly charges for the current FY but the app check is for an old budget. This also makes sense because if I don't use the app and just do an API create of an order using this fund, it works fine. So yes, I think you are probably right!

**Comment by fereira** [comment] 2022-08-09 14:08
I'm testing against the training server and seeing this: There is a budget for p2853-FY2022 *and* p2853-FY2023.  There is also one for p2651-FY2023 (29723.48 available) and there is a 2651-FY2023 (without the p) with 0.0 available.

We shouldn't be hardcoding the physical year in a properties file.  If it's not changed, the old budget would be used after the rollover to the new fiscal year.  Presumably, the current fiscal year is stored somewhere in folio and updated somehow.

**Comment by starsplatter** [comment] 2022-08-09 14:20
So I think they originally put this check into the app so that it wouldn't let people make orders on funds without budgets. But I think the chances of us doing that are relatively low. So we could either take out the hardcoding of the FY or just remove the budget check altogether. 

As far as selecting the current FY it looks to me like FOLIO only identifies it by date range and not by a flag indicating it is current. The FY has properties:

"periodStart": "2022-07-01T00:00:00.000+00:00",
"periodEnd": "2023-06-30T00:00:00.000+00:00",

from {{ okapi_url }}/finance/fiscal-years

**Comment by fereira** [comment] 2022-08-09 16:06
I think I can iterate over the fiscal year list and select the one for which the current date is in between periodStart and periodEnd.  I am doing something similar for the course reserves service.

**Comment by fereira** [comment] 2022-08-11 13:38
I've got an implementation of an API request that will return the current fiscal year based upon the period start dates.  However, in testing, I have encountered an issue with the order post request which I have created as issue #99

**Comment by fereira** [comment] 2022-08-15 15:52
This was fixed in the issue-96-redux branch that has been merged into main

**Closed by fereira** 2022-08-15 15:53 UTC
Labels: P1
