### ISSUE TITLE
Instance and PO line are sometimes mismatched

### ISSUE THREAD

**Issue by starsplatter** [cul-it/order-import-poc#32] opened 2021-05-04 20:32 UTC
If you click through to the instance from this PO line you'll see it goes to the wrong instance. I'm not sure where the mismatch is happening... I assume things are sometimes getting returned from FOLIO in a different order than we expect when we are creating things?

https://cornell-training.folio.ebsco.com/orders/view/574417f6-67c5-4bb6-9523-a2dd7eb2f795/po-line/view/483a2091-f707-4312-b01e-18b7f21876a8?qindex=poNumber&query=11633

**Comment by cappadona** [comment] 2021-05-04 20:55
Nice find...at least it's an instance that's meant for another PO line from the same PO. Have you been able to reliably reproduce this or is it intermittent?

**Comment by starsplatter** [comment] 2021-05-24 13:21
I was able to replicate this again this  morning with this file https://cornell.app.box.com/file/814186095745

**Comment by cappadona** [comment] 2021-05-24 13:50
Thanks. I ran into this last week as well.

**Comment by fereira** [comment] 2021-05-25 14:18
I've tracked down the issue but it will require a bit of a rewrite to fix it.   When posting a po to the API, poLines do not necessarily get saved on the server side (and assigned a poLine number) in the order included in the posted json.  The code was assuming that they did.   The fix will involve creating instance records from the updatedResponseJson rather than iterating over the marc a second time.  It's going to be messy.

**Comment by fereira** [comment] 2021-05-25 14:57
Wasn't as bad as I thought.  I have a fix for this and will push it once PR #44 is merged

**Comment by cappadona** [comment] 2021-05-25 18:07
@fereira I've included a fix for this with #45 although we still need to get the Instance Title in sync. I've shared my idea for that and requested your review.

**Comment by fereira** [comment] 2021-05-25 22:51
I figured out what the issue was with the instance not in sync.  When PO is submitted to the API, the poLines aren't necessarily created in the same order as they appear in the submitted JSON.  The code is iterating over the marc file a second time and using that index of the record to get the instanceId from the updatedPurchaseOrder json array, which has a different order of poLines.  Instead of iterating over the marc file, iterating over the updatedPurchaseOrder array will keep things in sync.  I'll review the PR #45 and see if I can apply that fix.  However,  that would have to be merged with changes made in PR #44

**Comment by cappadona** [comment] 2021-05-26 12:38
@fereira As part of #45, I'm [already retrieving](https://github.com/cul-it/order-import-poc/pull/45/files#diff-af6f15ce9a896f2ddcaed1bdef7adaaaedf62f50f22ddf70bd0e16ecf3166cfbR372-R374) the following from the`updatedPurchaseOrderJson` JSONObject:
* PO Line ID
* PO Line Number
* Instance ID

This ensures the PO Line and instance are in sync, so you shouldn't need to apply that fix, but since the response for `/orders/composite-orders/{id}` does not include the Instance Title, we still need to address that. I was considering building a map of PO Line ID to Instance Title, in order to avoid making additional API requests.

**Comment by fereira** [comment] 2021-05-26 13:29
You're missing the point of the comment I made.   If you're re-reading  marc file, and using numRec as an index to get the poLine ID, PO Line Number, and instance ID  from the updatePurchaseOrderJson then you're likely getting the wrong values.  

When the call to get the updatedPurchaseOrder is made, the order of the poLines is note necessarily the same as the order in which the records appear in the mark file.

**Comment by cappadona** [comment] 2021-05-26 21:36
@fereira and I met this afternoon and we have included a [temporary fix in #45](https://github.com/cul-it/order-import-poc/pull/45/commits/f9111c5f81506000b6b4e80002ae88126d754833), which he will refactor in the near future.

**Closed** 2021-05-27 12:28 UTC
Labels: P1, bug
